title: ""
labels: ["triage"]
body:
- type: markdown
  attributes:
    value: |
      ## Before you begin
      Please check the [discussions page](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/discussions) to see if a discussion already exists for your question, idea, etc.

      If you have a feature idea or have found a regression or bug, please open a [new issue](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/discussions/new/choose) instead.

      You can check out the project [wiki](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/wiki) for an install/post-install guide, as well guides for various fixes and improvements.

      ----
- type: dropdown
  id: variant
  attributes:
    label: Zenbook Duo Variant
    description: What variant(s) of the Zenbook Duo (14", 2019) are you using?
    multiple: true
    options:
      - i5/i7 UX481FL (with Nvidia MX250)
      - i5/i7 UX481FA (without Nvidia MX250)
  validations:
    required: true
- type: input
  id: opencore
  attributes:
    label: OpenCore Version
    description: |
      What version of OpenCore are you using?

      You can get the current OpenCore version on macOS by running the below command in Terminal:
      ```sh
      nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version
      ```
    placeholder: (Example) 0.8.6 Release or REL-086-2022-11-07
  validations:
    required: true
- type: dropdown
  id: macOS
  attributes:
    label: macOS Version
    description: What macOS version(s) are you seeing the problem on?
    multiple: true
    options:
      - Ventura (macOS 13)
      - Monterey (macOS 12)
      - Big Sur (macOS 11)
      - Catalina (macOS 10.15)
  validations:
    required: false
- type: textarea
  attributes:
    label: Body
    description: Start your discussion!
  validations:
    required: true