blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/discussions/new
    about: Please ask and answer questions here.